version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.cloud:google-cloud-bom
    versions:
    - 0.147.0
    - 0.148.0
    - 0.149.0
    - 0.150.0
    - 0.151.0
    - 0.152.0
  - dependency-name: com.restfb:restfb
    versions:
    - 3.13.0
    - 3.14.0
    - 3.15.0
    - 3.16.0
  - dependency-name: com.google.appengine:appengine-api-1.0-sdk
    versions:
    - 1.9.84
    - 1.9.85
    - 1.9.86
    - 1.9.87
  - dependency-name: org.json:json
    versions:
    - "20201115"
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
